name: Deploy Streamlit to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: nikitha-2025-1


      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev


      - name: Build and push Docker image
        run: |
          docker build --no-cache -t us-central1-docker.pkg.dev/nikitha-2025-1/streamlit-app/streamlit-app:latest .
          docker push us-central1-docker.pkg.dev/nikitha-2025-1/streamlit-app/streamlit-app:latest


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-app \
            --image us-central1-docker.pkg.dev/nikitha-2025-1/streamlit-app/streamlit-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars HF_TOKEN=${{ secrets.HF_TOKEN }} \
            --memory=2Gi

      - name: Print deployed URL
        run: |
          gcloud run services describe streamlit-app --region us-central1 --platform managed --format 'value(status.url)'
