name: Streamlit App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app.py

      - name: Run Streamlit app (test launch)
        run: |
          streamlit run app.py &
          sleep 10
          curl -I http://localhost:8502

      - name: Upload Streamlit logs
        if: always()
        run: |
          cat ~/.streamlit/logs/*.log || true

# Note: For deployment, use Streamlit Community Cloud or other hosting. This workflow only tests build and launch.
